Repository wishlists/wishlists, pull requests merged in 2020-10, with the labels that each got.

#30 add new test cases for error handlers in READ and CREATE api
  tests/test_service.py
Labels: enhancement

#41 Add LIST items API
  README.md
  service/service.py
  tests/factories.py
  tests/test_models.py
  tests/test_service.py
Labels: enhancement

#45 Update README.md
  README.md
Labels: documentation, technical debt

#77 Add metadata files for Cloud Foundry
  .travis.yml
  Procfile
  manifest.yml
  runtime.txt
Labels: technical debt
